### PR TITLE
fix incompatable labextensions

### PR DESCRIPTION
**Pull request by pindge**
fix `DcViewer` javascript issue

### CODE REVIEW

**Comment by benjimin** [comment]
There has been a number of environment changes at the same time, can someone please confirm if this PR is still needed (or close without merging if it is already fixed in current stable dev sandbox)? @emmaai

**Comment by benjimin** [comment]
Looks like 1.0.13 still needs fix
image

**Review by emmaai — CHANGES_REQUESTED** [review]
- `plotly` version is irrelevant
- no `ipywidgets==7.7.1` on conda, latest version is `7.6.5` and `ipywidgets` version is not an issue
- yes, `jupyterlab_widgets` need to `<2.0`

**Review by benjimin — APPROVED** [review]

**Review by emmaai — APPROVED** [review]

**Comment by benjimin** [comment]
Seems to work now, at least in latest/unstable.
image

**Pull request merged**
