### PR TITLE
jupyterhub version upgrade to 1.3.0

### PR DESCRIPTION
**Pull request by NikitaGandhi**
as part of jupyterhub upgrade, we need to upgrade `jupyterhub` version to `1.3.0`

### CODE REVIEW

**Review by mmochan — APPROVED** [review]
LGTM!

**Review by uchchwhash — APPROVED** [review]

**Review by mmochan — APPROVED** [review]
LGTM!

**Comment by Kirill888** [comment]
We can't merge this, as this won't work with current deployment that has older jupyterhub version.

**Comment by NikitaGandhi** [comment]
> We can't merge this, as this won't work with current deployment that has older jupyterhub version.

We are performing Jupyterhub upgrade tomorrow. Then we are planning to merge and also create a stable release.

**Comment by Kirill888** [comment]
that's great, but it ain't building anymore, cause things in the world moved on and we are not pinning things enough

**Comment by NikitaGandhi** [comment]
> that's great, but it ain't building anymore, cause things in the world moved on and we are not pinning things enough

oh, but it was working last week and manage to test `geoscienceaustralia/sandbox-dev:upgrade-jupyterhub-version` image.

**Comment by Kirill888** [comment]
Yep, but we updated base image to fix CVE, that in turn caused re-build of python environment, and in there this library
https://pypi.org/project/pysal/#history now no longer works on python 3.6

**Comment by NikitaGandhi** [comment]
> Yep, but we updated base image to fix CVE, that in turn caused re-build of python environment, and in there this library
> https://pypi.org/project/pysal/#history now no longer works on python 3.6

I saw you are making some quick fix. shell I wait until you complete it. We also need this change tomorrow

**Comment by Kirill888** [comment]
We'll see, hopefully it builds fine, I was also having issues with curl failing to fetch ffmpeg binary. But once it works fine it will be cached in a docker layer.

**Pull request merged**
