### PR TITLE
upgrade to jupyterlab > 4

### PR DESCRIPTION
**Pull request by emmaai**
Sorry I didn't look close enough when making that change. The conda version is not what I thought, and hence retrieve the installation.

### CODE REVIEW

**Comment by omad** [comment]
> Sorry I didn't look close enough when making that change. The conda version is not what I thought, and hence retrieve the installation.

What is the problem with the conda version?

It's important to know/record so we don't make the same (wrong) assumption in the future.

**Comment by emmaai** [comment]
> > Sorry I didn't look close enough when making that change. The conda version is not what I thought, and hence retrieve the installation.
> 
> What is the problem with the conda version?
> 
> It's important to know/record so we don't make the same (wrong) assumption in the future.

The awscliv2 on conda is a handler of invoking a pre-compiled image with awscli, not the tool itself.

**Comment by emmaai** [comment]
> > > Sorry I didn't look close enough when making that change. The conda version is not what I thought, and hence retrieve the installation.
> > 
> > 
> > What is the problem with the conda version?
> > It's important to know/record so we don't make the same (wrong) assumption in the future.
> 
> The awscliv2 on conda is a handler of invoking a pre-compiled image with awscli, not the tool itself.

noted in docker file

**Comment by stacyhorton** [comment]
As I mentioned to Robbi, I noticed some new error messages in the pod logs when launching an unstable server:


> 2024-08-28 12:38:52.537	2024-08-28 02:38:52,536 - ServerApp - ERROR - Uncaught exception GET /user/stacy.horton@ga.gov.au/github?1724812732141 (::ffff:10.95.1.179)
> 2024-08-28 12:38:52.537	HTTPServerRequest(protocol='http', host='app.sandbox.dea.ga.gov.au', method='GET', uri='/user/stacy.horton@ga.gov.au/github?1724812732141', version='HTTP/1.1', remote_ip='::ffff:10.95.1.179')
> 2024-08-28 12:38:52.537	Traceback (most recent call last):
> 2024-08-28 12:38:52.537	  File "/env/lib/python3.10/site-packages/tornado/web.py", line 1790, in _execute
> 2024-08-28 12:38:52.537	    result = await result
> 2024-08-28 12:38:52.537	  File "/env/lib/python3.10/site-packages/tornado/gen.py", line 234, in wrapper
> 2024-08-28 12:38:52.537	    yielded = ctx_run(next, result)
> 2024-08-28 12:38:52.537	  File "/env/lib/python3.10/site-packages/jupyterlab_github/__init__.py", line 95, in get
> 2024-08-28 12:38:52.537	    headers={"Authorization": "token {}".format(token)}
> 2024-08-28 12:38:52.537	UnboundLocalError: local variable 'token' referenced before assignment
> 2024-08-28 12:38:52.537	[W 2024-08-28 02:38:52.537 ServerApp] Unhandled error
> 2024-08-28 12:51:07.153	[W 2024-08-28 02:51:07.153 LabApp] Failed validating settings (jupyterlab-code-snippets:snippets): ['import matplotlib.pyplot as plt', 'import numpy as np', '', 'x = np.linspace(0, 10, 100)', '', 'plt.plot(x, np.sin(x))', 'plt.plot(x, np.cos(x))', '', 'plt.show()'] is not of type 'string'
> 2024-08-28 12:51:07.154
> 2024-08-28 12:51:07.154	    Failed validating 'type' in schema['properties']['snippets']['items']['properties']['code']:
> 2024-08-28 12:51:07.154	        {'title': 'Code', 'type': 'string'}
> 2024-08-28 12:51:07.154
> 2024-08-28 12:51:07.154	    On instance['snippets'][0]['code']:
> 2024-08-28 12:51:07.154	        ['import matplotlib.pyplot as plt',
> 2024-08-28 12:51:07.154	         'import numpy as np',
> 2024-08-28 12:51:07.154	         '',
> 2024-08-28 12:51:07.154	         'x = np.linspace(0, 10, 100)',
> 2024-08-28 12:51:07.154	         '',
> 2024-08-28 12:51:07.154	         'plt.plot(x, np.sin(x))',
> 2024-08-28 12:51:07.154	         'plt.plot(x, np.cos(x))',
> 2024-08-28 12:51:07.154	         '',
> 2024-08-28 12:51:07.154	         'plt.show()']
> 2024-08-28 12:51:09.146	[I 2024-08-28 02:51:09.146 LabApp] Build is up to date
> 2024-08-28 12:51:56.575	[W 2024-08-28 02:51:56.574 LabApp] wrote error: 'Schema not found: /env/share/jupyter/lab/schemas/@jupyterlab/codemirror-extension/commands.json'
> 2024-08-28 12:51:56.575	    Traceback (most recent call last):
> 2024-08-28 12:51:56.575	      File "/env/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
> 2024-08-28 12:51:56.575	        result = method(*self.path_args, **self.path_kwargs)
> 2024-08-28 12:51:56.575	      File "/env/lib/python3.10/site-packages/tornado/web.py", line 3301, in wrapper
> 2024-08-28 12:51:56.575	        return method(self, *args, **kwargs)
> 2024-08-28 12:51:56.575	      File "/env/lib/python3.10/site-packages/jupyterlab_server/settings_handler.py", line 58, in get
> 2024-08-28 12:51:56.575	        result, warnings = get_settings(
> 2024-08-28 12:51:56.575	      File "/env/lib/python3.10/site-packages/jupyterlab_server/settings_utils.py", line 385, in get_settings
> 2024-08-28 12:51:56.575	        schema, version = _get_schema(schemas_dir, schema_name, overrides, labextensions_path)
> 2024-08-28 12:51:56.575	      File "/env/lib/python3.10/site-packages/jupyterlab_server/settings_utils.py", line 61, in _get_schema
> 2024-08-28 12:51:56.575	        raise web.HTTPError(404, notfound_error % path)
> 2024-08-28 12:51:56.575	    tornado.web.HTTPError: HTTP 404: Not Found (Schema not found: /env/share/jupyter/lab/schemas/@jupyterlab/codemirror-extension/commands.json)
> 2024-08-28 12:51:56.583	[W 2024-08-28 02:51:56.582 LabApp] wrote error: 'Schema not found: /env/share/jupyter/lab/schemas/@jupyterlab/toc-extension/plugin.json'
> 2024-08-28 12:51:56.583	    Traceback (most recent call last):
> 2024-08-28 12:51:56.583	      File "/env/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
> 2024-08-28 12:51:56.583	        result = method(*self.path_args, **self.path_kwargs)
> 2024-08-28 12:51:56.583	      File "/env/lib/python3.10/site-packages/tornado/web.py", line 3301, in wrapper
> 2024-08-28 12:51:56.583	        return method(self, *args, **kwargs)
> 2024-08-28 12:51:56.583	      File "/env/lib/python3.10/site-packages/jupyterlab_server/settings_handler.py", line 58, in get
> 2024-08-28 12:51:56.583	        result, warnings = get_settings(
> 2024-08-28 12:51:56.583	      File "/env/lib/python3.10/site-packages/jupyterlab_server/settings_utils.py", line 385, in get_settings
> 2024-08-28 12:51:56.583	        schema, version = _get_schema(schemas_dir, schema_name, overrides, labextensions_path)
> 2024-08-28 12:51:56.583	      File "/env/lib/python3.10/site-packages/jupyterlab_server/settings_utils.py", line 61, in _get_schema
> 2024-08-28 12:51:56.583	        raise web.HTTPError(404, notfound_error % path)
> 2024-08-28 12:51:56.583	    tornado.web.HTTPError: HTTP 404: Not Found (Schema not found: /env/share/jupyter/lab/schemas/@jupyterlab/toc-extension/plugin.json)
> 2024-08-28 12:51:57.517	[I 2024-08-28 02:51:57.517 ServerApp] New terminal with automatic name: 1
> 2024-08-28 12:51:58.165	[W 2024-08-28 02:51:58.164 ServerApp] Notebook DEA_Sandbox.ipynb is not trusted
> 2024-08-28 12:51:58.173	[W 2024-08-28 02:51:58.172 LabApp] wrote error: 'Schema not found: /env/share/jupyter/lab/schemas/@jupyterlab/application-extension/sidebar.json'
> 2024-08-28 12:51:58.173	    Traceback (most recent call last):
> 2024-08-28 12:51:58.173	      File "/env/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
> 2024-08-28 12:51:58.173	        result = method(*self.path_args, **self.path_kwargs)
> 2024-08-28 12:51:58.173	      File "/env/lib/python3.10/site-packages/tornado/web.py", line 3301, in wrapper
> 2024-08-28 12:51:58.173	        return method(self, *args, **kwargs)
> 2024-08-28 12:51:58.173	      File "/env/lib/python3.10/site-packages/jupyterlab_server/settings_handler.py", line 58, in get
> 2024-08-28 12:51:58.173	        result, warnings = get_settings(
> 2024-08-28 12:51:58.173	      File "/env/lib/python3.10/site-packages/jupyterlab_server/settings_utils.py", line 385, in get_settings
> 2024-08-28 12:51:58.173	        schema, version = _get_schema(schemas_dir, schema_name, overrides, labextensions_path)
> 2024-08-28 12:51:58.173	      File "/env/lib/python3.10/site-packages/jupyterlab_server/settings_utils.py", line 61, in _get_schema
> 2024-08-28 12:51:58.173	        raise web.HTTPError(404, notfound_error % path)
> 2024-08-28 12:51:58.173	    tornado.web.HTTPError: HTTP 404: Not Found (Schema not found: /env/share/jupyter/lab/schemas/@jupyterlab/application-extension/sidebar.json)

**Comment by robbibt** [comment]
@emmaai Any thoughts on what might be causing/how we could resolve those issues in the logs that Stacy shared above?

**Comment by emmaai** [comment]
When you don't clean your cache...it may happen. The js of jupyterlab is
different between 3 and 4. It'd be gone if the cache is cleared between stable and unstable profile switching.

**Review by robbibt — APPROVED** [review]
Looks great, let's merge this.

**Pull request merged**
